// Code generated by protoc-gen-go. DO NOT EDIT.
// source: viz.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkInterface struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IPAddress            string   `protobuf:"bytes,2,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInterface) Reset()         { *m = NetworkInterface{} }
func (m *NetworkInterface) String() string { return proto.CompactTextString(m) }
func (*NetworkInterface) ProtoMessage()    {}
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a3c9003629df19, []int{0}
}

func (m *NetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterface.Unmarshal(m, b)
}
func (m *NetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterface.Marshal(b, m, deterministic)
}
func (m *NetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterface.Merge(m, src)
}
func (m *NetworkInterface) XXX_Size() int {
	return xxx_messageInfo_NetworkInterface.Size(m)
}
func (m *NetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterface proto.InternalMessageInfo

func (m *NetworkInterface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkInterface) GetIPAddress() string {
	if m != nil {
		return m.IPAddress
	}
	return ""
}

type Host struct {
	Hostname             string              `protobuf:"bytes,1,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	OS                   string              `protobuf:"bytes,2,opt,name=OS,proto3" json:"OS,omitempty"`
	Architecture         string              `protobuf:"bytes,3,opt,name=Architecture,proto3" json:"Architecture,omitempty"`
	MachineID            string              `protobuf:"bytes,4,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	Interfaces           []*NetworkInterface `protobuf:"bytes,5,rep,name=Interfaces,proto3" json:"Interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a3c9003629df19, []int{1}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Host) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *Host) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *Host) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *Host) GetInterfaces() []*NetworkInterface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type Packet struct {
	Protocol             string               `protobuf:"bytes,1,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	SrcAddr              string               `protobuf:"bytes,2,opt,name=SrcAddr,proto3" json:"SrcAddr,omitempty"`
	DstAddr              string               `protobuf:"bytes,3,opt,name=DstAddr,proto3" json:"DstAddr,omitempty"`
	SrcPort              int32                `protobuf:"varint,4,opt,name=SrcPort,proto3" json:"SrcPort,omitempty"`
	DstPort              int32                `protobuf:"varint,5,opt,name=DstPort,proto3" json:"DstPort,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	PktSize              int32                `protobuf:"varint,7,opt,name=PktSize,proto3" json:"PktSize,omitempty"`
	MachineID            string               `protobuf:"bytes,8,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a3c9003629df19, []int{2}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Packet) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *Packet) GetDstAddr() string {
	if m != nil {
		return m.DstAddr
	}
	return ""
}

func (m *Packet) GetSrcPort() int32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Packet) GetDstPort() int32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *Packet) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Packet) GetPktSize() int32 {
	if m != nil {
		return m.PktSize
	}
	return 0
}

func (m *Packet) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

type Reply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a3c9003629df19, []int{3}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NetworkInterface)(nil), "pb.NetworkInterface")
	proto.RegisterType((*Host)(nil), "pb.Host")
	proto.RegisterType((*Packet)(nil), "pb.Packet")
	proto.RegisterType((*Reply)(nil), "pb.Reply")
}

func init() { proto.RegisterFile("viz.proto", fileDescriptor_d9a3c9003629df19) }

var fileDescriptor_d9a3c9003629df19 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x4d, 0x8f, 0x94, 0x40,
	0x10, 0x95, 0xf9, 0x80, 0xa1, 0xd6, 0x18, 0xd3, 0xf1, 0xd0, 0x21, 0x26, 0x22, 0xf1, 0xc0, 0x89,
	0x49, 0x46, 0x0f, 0x5e, 0xd7, 0x9d, 0x83, 0x1c, 0x66, 0x97, 0x80, 0xf1, 0xe0, 0x0d, 0x7a, 0x6b,
	0x67, 0x08, 0x0c, 0x4d, 0xba, 0x7b, 0x35, 0xce, 0x4f, 0xf2, 0x47, 0x1a, 0xd3, 0x0d, 0xcd, 0x38,
	0x73, 0x82, 0x57, 0xaf, 0xaa, 0xfa, 0xd5, 0x7b, 0xe0, 0xff, 0xac, 0x4f, 0x49, 0x2f, 0xb8, 0xe2,
	0x64, 0xd6, 0x57, 0xc1, 0xbb, 0x3d, 0xe7, 0xfb, 0x16, 0xd7, 0xa6, 0x52, 0x3d, 0x3f, 0xad, 0x55,
	0x7d, 0x44, 0xa9, 0xca, 0x63, 0x3f, 0x34, 0x45, 0x5b, 0x78, 0x7d, 0x8f, 0xea, 0x17, 0x17, 0x4d,
	0xda, 0x29, 0x14, 0x4f, 0x25, 0x43, 0x42, 0x60, 0x71, 0x5f, 0x1e, 0x91, 0x3a, 0xa1, 0x13, 0xfb,
	0xb9, 0xf9, 0x27, 0x6f, 0xc1, 0x4f, 0xb3, 0xdb, 0xc7, 0x47, 0x81, 0x52, 0xd2, 0x99, 0x21, 0xce,
	0x85, 0xe8, 0x8f, 0x03, 0x8b, 0xaf, 0x5c, 0x2a, 0x12, 0xc0, 0x4a, 0x7f, 0xbb, 0xf3, 0xf8, 0x84,
	0xc9, 0x2b, 0x98, 0x3d, 0x14, 0xe3, 0xec, 0xec, 0xa1, 0x20, 0x11, 0xbc, 0xbc, 0x15, 0xec, 0x50,
	0x2b, 0x64, 0xea, 0x59, 0x20, 0x9d, 0x1b, 0xe6, 0xa2, 0xa6, 0x9f, 0xdd, 0x95, 0xec, 0x50, 0x77,
	0x98, 0x6e, 0xe9, 0x62, 0x78, 0x76, 0x2a, 0x90, 0x4f, 0x00, 0x93, 0x6a, 0x49, 0x97, 0xe1, 0x3c,
	0xbe, 0xd9, 0xbc, 0x49, 0xfa, 0x2a, 0xb9, 0x3e, 0x29, 0xff, 0xaf, 0x2f, 0xfa, 0xeb, 0x80, 0x9b,
	0x95, 0xac, 0x41, 0x23, 0x37, 0xd3, 0x36, 0x30, 0xde, 0x5a, 0xb9, 0x16, 0x13, 0x0a, 0x5e, 0x21,
	0x98, 0xbe, 0x70, 0xd4, 0x6c, 0xa1, 0x66, 0xb6, 0x52, 0x19, 0x66, 0xd0, 0x6c, 0xe1, 0x38, 0x93,
	0x71, 0xa1, 0x8c, 0xd8, 0x65, 0x6e, 0xe1, 0x38, 0x63, 0x98, 0xe5, 0xc0, 0x8c, 0x90, 0x7c, 0x06,
	0xff, 0x9b, 0x0d, 0x85, 0xba, 0xa1, 0x13, 0xdf, 0x6c, 0x82, 0x64, 0x88, 0x2d, 0xb1, 0xb1, 0x25,
	0x53, 0x47, 0x7e, 0x6e, 0xd6, 0x3b, 0xb3, 0x46, 0x15, 0xf5, 0x09, 0xa9, 0x37, 0xec, 0x1c, 0xe1,
	0xa5, 0x6d, 0xab, 0x2b, 0xdb, 0xa2, 0xf7, 0xb0, 0xcc, 0xb1, 0x6f, 0x7f, 0xeb, 0x05, 0x3b, 0x94,
	0xb2, 0xdc, 0xdb, 0xb0, 0x2c, 0xdc, 0xec, 0x60, 0xfe, 0xbd, 0x3e, 0x91, 0x0f, 0xe0, 0xdd, 0xf1,
	0xb6, 0x45, 0xa6, 0x08, 0x68, 0x5f, 0x07, 0xdb, 0x02, 0x5f, 0xff, 0x9b, 0x15, 0xd1, 0x8b, 0xd8,
	0x21, 0x21, 0x78, 0x77, 0x07, 0x64, 0x4d, 0xda, 0x91, 0x95, 0x66, 0x74, 0xe2, 0x17, 0x3d, 0x5f,
	0xdc, 0x1f, 0x8b, 0x64, 0xdd, 0x57, 0x95, 0x6b, 0x0e, 0xfa, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x3b, 0x26, 0x99, 0xa6, 0x02, 0x00, 0x00,
}
